### ISSUE TITLE
master not working

### ISSUE THREAD

**Issue by aschor** [sylcastaing/hass-qubino-flush-pilot-wire-card#77]
Hi, I tried to follow the guidelines, as is. for a start.

npm install
npm start
=> add ressource to home assistant (http://local-dev-ip/qubino-flush-wire-pilot.js) , add the card to the dashboard and .... I see nothing.

npm run lint
npm build

I copy the file over home assistant www folder. change the ressource to /local/...Etc
... and I see nothing in my dashboard.

OK. So I open webconsole, and there are A LOT of errors, for example :
Uncaught (in promise) TypeError: e.config is undefined

any hint please ? npm build spits no error ...

**Comment by aschor** [comment]
yes, the file found inside the zip in the setup section works. 

But I'm willing to modify the card. and the generated .js file does not work.  I'm just following the "dev" section with master files, should'nt this generate a working .js file ?

Here is something that got generated with clean git cloned repo :

[qubino-flush-wire-pilot.zip](https://github.com/sylcastaing/hass-qubino-flush-pilot-wire-card/files/5982462/qubino-flush-wire-pilot.zip)

I'm trying it on 
supervisor-2021.02.6
core-2021.2.3
Home Assistant OS 5.11

(and firefox)

**Comment by sylcastaing** [comment]
Ok, what's your hass config ?

**If you only want to build on your computer :**
- `npm build`

and config with output file on `dist`
```yaml
resources:
  # add ?v parameter to invalid cache in case of update
  - url: /local/qubino-flush-wire-pilot.js?v=1.0.0
    type: module
```

**If you want to dev and show change on hass**
- `npm start`

and config
```yaml
#ui-lovelace.yaml
resources:
  - url: http://${IP_ADDRESS}:5000/qubino-flush-wire-pilot.js
    type: module
```

`IP_ADDRESS` is ip of your computer.
